# Permalinks
permalink:        pretty

# Setup
title:            Hydejack
tagline:          Better than lumber jack.
description:      >
  A pretentious two-column <a href="http://jekyllrb.com/">Jekyll</a>
  theme, stolen by <a href="https://twitter.com/qwtel" target="_blank">@qwtel</a>
  from <a href="http://hyde.getpoole.com">Hyde</a>.
  You could say it was.. <a href="http://media3.giphy.com/media/makedRIckZBW8/giphy.gif">hydejacked</a>.

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

url:              https://qwtel.com
baseurl:          /hydejack

author:
  name:           'Florian Klampfer'
  url:            https://qwtel.github.io
  twitter:        qwtel
  github:         qwtel

# Fallback image and color if not overwritten for tag or post
# image:            none
color:            '#268bd2'

kramdown:
  extensions:
    - autolink
